#!/usr/bin/env python3
"""Plot presentation detail panels for the real patched split-K selector.

The top panel compares speedup against FlashInfer default. The bottom panel
compares the selected number of split-K chunks. Input data is generated by
compare_patched_results.py from real patched benchmark results.

Usage:
    cd /root/capstone-yonsei
    /root/capstone-yonsei/venv/bin/python \
      splitk_heuristic_simulation/plot_presentation_batch_detail.py \
      --model llama3_8b --batch-size 4
"""

from __future__ import annotations

import argparse
import csv
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker


ROOT = Path(__file__).resolve().parents[1]
DETAILS_CSV = (
    ROOT
    / "splitk_heuristic_simulation"
    / "results"
    / "data"
    / "llama3_8b_real_patched_comparison_details.csv"
)
OUT_DIR = ROOT / "splitk_heuristic_simulation" / "results" / "plots" / "presentation"

DEFAULT_COLOR = "#1f77b4"
HEURISTIC_COLOR = "#2ca02c"
ORACLE_COLOR = "#ff7f0e"


def format_kv_axis(ax, max_kv_len: int) -> None:
    ax.set_xlim(left=0, right=max_kv_len + 256)
    ax.xaxis.set_major_locator(ticker.MultipleLocator(1024))
    ax.xaxis.set_major_formatter(
        ticker.FuncFormatter(lambda x, _: f"{int(x / 1024)}K" if x >= 1024 else "")
    )
    ax.xaxis.set_minor_locator(ticker.MultipleLocator(128))
    ax.xaxis.set_minor_formatter(ticker.NullFormatter())


def load_details(path: Path) -> list[dict[str, float]]:
    numeric_cols = [
        "batch_size",
        "kv_len",
        "default_chunks",
        "patched_chunks",
        "oracle_chunks",
        "patched_speedup",
        "oracle_speedup",
    ]
    with path.open(newline="") as stream:
        rows = list(csv.DictReader(stream))
    for row in rows:
        for col in numeric_cols:
            row[col] = float(row[col])
    return rows


def plot_batch_detail(details: list[dict[str, float]], model: str, batch_size: int, out_dir: Path) -> Path:
    batch = sorted(
        (row for row in details if int(row["batch_size"]) == batch_size),
        key=lambda row: row["kv_len"],
    )
    if not batch:
        available = sorted({int(row["batch_size"]) for row in details})
        raise SystemExit(f"no rows found for BS={batch_size}. available: {available}")

    kv_len = [row["kv_len"] for row in batch]
    max_kv_len = int(max(kv_len))
    fig, axes = plt.subplots(
        2,
        1,
        figsize=(15.62, 9.78),
        sharex=True,
        gridspec_kw={"height_ratios": [1.12, 1.0], "hspace": 0.10},
    )
    ax_speedup, ax_chunks = axes

    ax_speedup.plot(
        kv_len,
        [1.0] * len(batch),
        color=DEFAULT_COLOR,
        ls="--",
        lw=1.7,
        label="FlashInfer Default",
    )
    ax_speedup.plot(
        kv_len,
        [row["patched_speedup"] for row in batch],
        color=HEURISTIC_COLOR,
        lw=2.0,
        marker="o",
        ms=3.0,
        label="New Heuristic",
    )
    ax_speedup.plot(
        kv_len,
        [row["oracle_speedup"] for row in batch],
        color=ORACLE_COLOR,
        lw=2.0,
        marker="o",
        ms=3.0,
        label="Oracle",
    )
    ax_speedup.set_ylabel("Latency Speedup")
    ax_speedup.set_title("Speedup vs FlashInfer Default", fontsize=13, fontweight="bold")
    ax_speedup.legend(loc="upper right", frameon=True)

    ax_chunks.plot(
        kv_len,
        [row["default_chunks"] for row in batch],
        color=DEFAULT_COLOR,
        lw=2.0,
        marker="o",
        ms=3.0,
        label="FlashInfer Default",
    )
    ax_chunks.plot(
        kv_len,
        [row["patched_chunks"] for row in batch],
        color=HEURISTIC_COLOR,
        lw=2.0,
        marker="o",
        ms=3.0,
        label="New Heuristic",
    )
    ax_chunks.plot(
        kv_len,
        [row["oracle_chunks"] for row in batch],
        color=ORACLE_COLOR,
        lw=2.0,
        marker="o",
        ms=3.0,
        label="Oracle",
    )
    ax_chunks.set_ylabel("# of Split-K Chunks")
    ax_chunks.set_xlabel("KV Length")
    ax_chunks.set_title("Selected Split-K Chunks", fontsize=13, fontweight="bold")
    max_chunks = max(
        max(row["default_chunks"], row["patched_chunks"], row["oracle_chunks"])
        for row in batch
    )
    chunk_axis_top = max(8, int(math.ceil(max_chunks / 4.0) * 4))
    ax_chunks.set_ylim(0, chunk_axis_top)
    ax_chunks.yaxis.set_major_locator(ticker.MaxNLocator(integer=True))
    ax_chunks.legend(loc="upper left", frameon=True)

    for ax in axes:
        format_kv_axis(ax, max_kv_len)
        ax.grid(True, which="both", ls=":", alpha=0.42)

    fig.suptitle(
        f"{model} BS={batch_size}: New Split-K Heuristic Behavior",
        fontsize=16,
        fontweight="bold",
    )
    fig.text(
        0.5,
        0.012,
        "Oracle selects the lowest-latency split-K setting at each KV length; results use the real patched scheduler benchmark.",
        ha="center",
        fontsize=9,
    )

    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{model}_bs{batch_size}_new_heuristic_presentation_detail.png"
    fig.subplots_adjust(left=0.075, right=0.985, bottom=0.10, top=0.90, hspace=0.14)
    fig.savefig(out, dpi=220)
    plt.close(fig)
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot presentation detail for the real patched split-K selector.")
    parser.add_argument("--details-csv", type=Path, default=DETAILS_CSV)
    parser.add_argument("--model", default="llama3_8b")
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--out-dir", type=Path, default=OUT_DIR)
    args = parser.parse_args()

    details = load_details(args.details_csv)
    out = plot_batch_detail(details, args.model, args.batch_size, args.out_dir)
    print(f"saved: {out}")


if __name__ == "__main__":
    main()
